name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: sudo npm ci
    - name: install
      run: sudo npm i
    - name: check tsc version
      run: tsc --version
    - name: Delete dist folder
      run: sudo rm -rf /home/ubuntu/backend/_work/node-yml/node-yml/dist
    - name: Build tsc
      run: sudo tsc
    - name: aws cmd
      run: sudo systemctl restart backend
    
    